const data = {
    product:[
        {
            _id:'1',
            name: 'Burn Mate Iced Tea',
            category: 'Beverages',
            image: '/Product Pictures/BurnMateIcedTea.png',
            price: 770,
            brand: 'Burn' , 
            rating:4.5,
            numReviews:10,
            description: 'Here’s a refreshingly healthy way to lose weight and burn that extra calories. Burn Mate Iced Tea is a drink that you and your body will surely enjoy!',
        },
        {
            _id:'2',
            name: 'Burn Shake',
            category: 'Beverages',
            image: '/Product Pictures/BurnShake.png',
            price: 950,
            brand: 'Burn' , 
            rating:5,
            numReviews:10,
            description: 'Here’s a refreshingly healthy way to lose weight and burn that extra calories. Burn Mate Iced Tea is a drink that you and your body will surely enjoy!',
        },
        {
            _id:'3',
            name: 'Liven Cappuccino',
            category: 'Coffee',
            image: '/Product Pictures/Liven Cappuccino.png',
            price: 320,
            brand: 'Liven' , 
            rating:4.5,
            numReviews:14,
            description: 'Here’s a refreshingly healthy way to lose weight and burn that extra calories. Burn Mate Iced Tea is a drink that you and your body will surely enjoy!',
        },
        {
            _id:'4',
            name: 'Liven Burn Coffee',
            category: 'Coffee',
            image: '/Product Pictures/LivenBurnCoffee.png',
            price: 420,
            brand: 'Liven' , 
            rating:4.5,
            numReviews:12,
            description: 'Here’s a refreshingly healthy way to lose weight and burn that extra calories. Burn Mate Iced Tea is a drink that you and your body will surely enjoy!',
        },
        {
            _id:'5',
            name: 'Liven Original',
            category: 'Coffee',
            image: '/Product Pictures/LiveOriginal.png',
            price: 320,
            brand: 'Liven' , 
            rating:4.5,
            numReviews:10,
            description: 'Here’s a refreshingly healthy way to lose weight and burn that extra calories. Burn Mate Iced Tea is a drink that you and your body will surely enjoy!',
        },
        {
            _id:'6',
            name: 'Liven Latte',
            category: 'Coffee',
            image: '/Product Pictures/LivenLatte.png',
            price: 320,
            brand: 'Liven' , 
            rating:4.5,
            numReviews:15,
            description: 'Here’s a refreshingly healthy way to lose weight and burn that extra calories. Burn Mate Iced Tea is a drink that you and your body will surely enjoy!',
        },
    ],
};
export default data;